# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [3]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [4]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [5]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [6]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [7]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [8]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [10]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [11]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [12]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [5]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.72701945 0.97351345 0.62515315 0.58160225 0.10455136]
 [0.71222172 0.09936295 0.8436925  0.37612595 0.47876814]
 [0.94488825 0.01936594 0.87947985 0.76456747 0.3308887 ]
 [0.26536195 0.55277695 0.3938248  0.69210543 0.57275651]
 [0.60506027 0.60274286 0.69579936 0.71850699 0.67638926]]

[[-1.38205835  0.6420495  -0.6743927  -1.18660804  0.59370605]
 [ 0.76826428  0.96879326  1.04324868 -1.00551435  2.03643188]
 [-1.75564675 -0.21043693  1.81143486  0.35541523 -1.0803877 ]
 [-1.16448852  0.71227267  1.25401717 -0.75110403  0.7587289 ]
 [ 0.21599161 -0.69175183 -0.65594961  0.0239917  -0.29559189]
 [-1.01749062  0.4737998   1.77709976 -1.10001107  0.38495929]
 [ 0.78527168  0.924605   -0.70613982 -1.18556873  0.84676375]
 [ 0.7704146  -0.68563045 -0.95261198  0.46021352 -0.47790834]
 [ 1.69212654 -1.38371059  0.64647422  0.99727198 -1.01421262]
 [-0.6168112  -0.09592171 -0.03952005 -1.07234365 -0.24003902]]


In [14]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5554073969525004
1.0472600814215451


In [15]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.02110895910945476
2.1259170645305243


In [16]:
# break here for next video!

In [17]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.94028947  0.60000398  1.41285855 -1.5134235  -0.88021491  0.94135611
 -1.80239683  0.66629612 -1.01911151  0.21159833 -1.03155549 -0.85369276
  0.2238648  -0.5560198   1.12184982  1.25141177 -0.82040704  1.2201986
 -0.08866664]
-1.8023968291899437


In [18]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-0.88021491  0.94135611 -1.80239683  0.66629612 -1.01911151]


In [19]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.94028947 -1.5134235  -1.80239683  0.21159833  0.2238648 ]


In [20]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.95460613 0.47729939 0.11738834 0.02110896 0.05133451]
 [0.12904    0.85419409 0.22023835 0.75901833 0.05471215]
 [0.43330101 0.06016668 0.8543437  0.7402433  0.96687139]
 [0.36714662 0.93693197 0.89404087 0.86315755 0.38816278]
 [0.64814517 0.761626   0.84733851 0.9292506  0.55551853]]
0.22023834980968215
0.22023834980968215


In [21]:
print(rand_mat[0:2,1:3])

[[0.47729939 0.11738834]
 [0.85419409 0.22023835]]


In [22]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.94028947  0.60000398  1.41285855 -1.5134235  -0.88021491  0.94135611
 -1.80239683  0.66629612 -1.01911151  0.21159833 -1.03155549 -0.85369276
  0.2238648  -0.5560198   1.12184982  1.25141177 -0.82040704  1.2201986
 -0.08866664]

[ 0.94028947  0.60000398  1.41285855  4.          4.          0.94135611
 -1.80239683  0.66629612 -1.01911151  0.21159833 -1.03155549 -0.85369276
  0.2238648  -0.5560198   1.12184982  1.25141177 -0.82040704  1.2201986
 -0.08866664]

[ 0.94028947  0.60000398  1.41285855  1.          2.          0.94135611
 -1.80239683  0.66629612 -1.01911151  0.21159833 -1.03155549 -0.85369276
  0.2238648  -0.5560198   1.12184982  1.25141177 -0.82040704  1.2201986
 -0.08866664]


In [23]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.95460613 0.47729939 0.11738834 0.02110896 0.05133451]
 [0.12904    0.85419409 0.22023835 0.75901833 0.05471215]
 [0.43330101 0.06016668 0.8543437  0.7402433  0.96687139]
 [0.36714662 0.93693197 0.89404087 0.86315755 0.38816278]
 [0.64814517 0.761626   0.84733851 0.9292506  0.55551853]]

[[0.95460613 0.47729939 0.11738834 0.02110896 0.05133451]
 [0.12904    0.85419409 0.22023835 0.         0.        ]
 [0.43330101 0.06016668 0.8543437  0.         0.        ]
 [0.36714662 0.93693197 0.89404087 0.86315755 0.38816278]
 [0.64814517 0.761626   0.84733851 0.9292506  0.55551853]]


In [24]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.95460613 0.47729939 0.11738834]
 [0.12904    0.85419409 0.22023835]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [25]:
print(rand_mat)

[[3.         3.         3.         0.02110896 0.05133451]
 [3.         3.         3.         0.         0.        ]
 [0.43330101 0.06016668 0.8543437  0.         0.        ]
 [0.36714662 0.93693197 0.89404087 0.86315755 0.38816278]
 [0.64814517 0.761626   0.84733851 0.9292506  0.55551853]]


In [26]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.02110896 0.05133451]
 [3.         3.         3.         0.         0.        ]
 [0.43330101 0.06016668 0.8543437  0.         0.        ]
 [0.36714662 0.93693197 0.89404087 0.86315755 0.38816278]
 [0.64814517 0.761626   0.84733851 0.9292506  0.55551853]]


In [27]:
# break here for next video

In [28]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.03559796 -0.62355608 -1.03070823  2.57382108  1.77600889 -1.20761361
 -0.81519466  0.80695994  0.07383944 -0.64224086  0.23079906 -1.11461499
 -0.91084784 -0.1664841   0.64371767]
[ True False False  True  True False False  True  True False  True False
 False False  True]
[0.03559796 2.57382108 1.77600889 0.80695994 0.07383944 0.23079906
 0.64371767]


In [29]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.08008537 -0.29055657  0.45963565 -1.16412794  1.13433904]
 [ 0.4069099   0.10956186  0.56094992 -1.21980603  0.23271308]
 [-1.56306095  1.84375483  0.03661978  0.68510085 -1.49809723]
 [-0.0181263   2.12591706  0.69235765 -0.07709297  0.00832227]
 [-0.37910105  0.11229938  1.22418944  0.83978513 -0.65923094]
 [ 1.39297736  0.938927    1.68609064 -1.41408506 -1.50970979]
 [-1.50644832  0.05393733 -1.61339834 -0.72540804 -1.52853402]
 [-0.18149447 -0.52846656 -0.35904172 -0.24658416 -0.85929869]
 [-0.46462674 -0.65884971  0.15737554 -1.07947434  1.30137673]
 [ 1.77411311  0.07280053  1.88423463 -1.80702343  1.04223275]]
[0.45963565 1.13433904 0.4069099  0.10956186 0.56094992 0.23271308
 1.84375483 0.03661978 0.68510085 2.12591706 0.69235765 0.00832227
 0.11229938 1.22418944 0.83978513 1.39297736 0.938927   1.68609064
 0.05393733 0.15737554 1.30137673 1.77411311 0.07280053 1.88423463
 1.04223275]


In [30]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 0.03559796 -0.62355608 -1.03070823  2.57382108  1.77600889 -1.20761361
 -0.81519466  0.80695994  0.07383944 -0.64224086  0.23079906 -1.11461499
 -0.91084784 -0.1664841   0.64371767]

[ 0.03559796 -0.62355608 -1.03070823 -5.         -5.         -1.20761361
 -0.81519466 -5.          0.07383944 -0.64224086  0.23079906 -1.11461499
 -0.91084784 -0.1664841  -5.        ]


In [31]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [32]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [33]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.08008537 -0.29055657  0.45963565 -1.16412794  1.13433904]
 [ 0.4069099   0.10956186  0.56094992 -1.21980603  0.23271308]
 [-1.56306095  1.84375483  0.03661978  0.68510085 -1.49809723]
 [-0.0181263   2.12591706  0.69235765 -0.07709297  0.00832227]
 [-0.37910105  0.11229938  1.22418944  0.83978513 -0.65923094]
 [ 1.39297736  0.938927    1.68609064 -1.41408506 -1.50970979]
 [-1.50644832  0.05393733 -1.61339834 -0.72540804 -1.52853402]
 [-0.18149447 -0.52846656 -0.35904172 -0.24658416 -0.85929869]
 [-0.46462674 -0.65884971  0.15737554 -1.07947434  1.30137673]
 [ 1.77411311  0.07280053  1.88423463 -1.80702343  1.04223275]]



In [34]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.02110896 0.05133451]
 [3.         3.         3.         0.         0.        ]
 [0.43330101 0.06016668 0.8543437  0.         0.        ]
 [0.36714662 0.93693197 0.89404087 0.86315755 0.38816278]
 [0.64814517 0.761626   0.84733851 0.9292506  0.55551853]]

[[-0.08008537 -0.29055657  0.45963565 -1.16412794  1.13433904]
 [ 0.4069099   0.10956186  0.56094992 -1.21980603  0.23271308]
 [-1.56306095  1.84375483  0.03661978  0.68510085 -1.49809723]
 [-0.0181263   2.12591706  0.69235765 -0.07709297  0.00832227]
 [-0.37910105  0.11229938  1.22418944  0.83978513 -0.65923094]
 [ 1.39297736  0.938927    1.68609064 -1.41408506 -1.50970979]
 [-1.50644832  0.05393733 -1.61339834 -0.72540804 -1.52853402]
 [-0.18149447 -0.52846656 -0.35904172 -0.24658416 -0.85929869]
 [-0.46462674 -0.65884971  0.15737554 -1.07947434  1.30137673]
 [ 1.77411311  0.07280053  1.88423463 -1.80702343  1.04223275]]
[[3.         3.         3.         0.02110896 0.05133451]
 [3.         3.    

In [35]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.02110896 0.05133451]
 [3.         3.         3.         0.         0.        ]
 [0.43330101 0.06016668 0.8543437  0.         0.        ]
 [0.36714662 0.93693197 0.89404087 0.86315755 0.38816278]
 [0.64814517 0.761626   0.84733851 0.9292506  0.55551853]]

[[3.         3.         3.         0.02110896 0.05133451]
 [3.         3.         3.         0.         0.        ]
 [0.43330101 0.06016668 0.8543437  0.         0.        ]
 [0.36714662 0.93693197 0.89404087 0.86315755 0.38816278]
 [0.64814517 0.761626   0.84733851 0.9292506  0.55551853]]
